// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db_access

import (
	"context"
	"database/sql"
)

const addPerson = `-- name: AddPerson :execlastid
INSERT INTO person (first_name, last_name, notes) VALUES (?, ?, ?)
`

type AddPersonParams struct {
	FirstName string
	LastName  string
	Notes     sql.NullString
}

func (q *Queries) AddPerson(ctx context.Context, arg AddPersonParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addPerson, arg.FirstName, arg.LastName, arg.Notes)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const addPhone = `-- name: AddPhone :exec
INSERT INTO phone (phone_number, phone_type, person_id) VALUES (?, ?, ?)
`

type AddPhoneParams struct {
	PhoneNumber string
	PhoneType   int32
	PersonID    int32
}

func (q *Queries) AddPhone(ctx context.Context, arg AddPhoneParams) error {
	_, err := q.db.ExecContext(ctx, addPhone, arg.PhoneNumber, arg.PhoneType, arg.PersonID)
	return err
}

const getAllPersons = `-- name: GetAllPersons :many
SELECT id, first_name, last_name, notes FROM person
`

type GetAllPersonsRow struct {
	ID        int32
	FirstName string
	LastName  string
	Notes     sql.NullString
}

func (q *Queries) GetAllPersons(ctx context.Context) ([]GetAllPersonsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPersons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPersonsRow
	for rows.Next() {
		var i GetAllPersonsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPersonByFname = `-- name: GetPersonByFname :many
SELECT id, first_name, last_name, notes FROM person WHERE first_name LIKE CONCAT('%', ?, '%')
`

type GetPersonByFnameRow struct {
	ID        int32
	FirstName string
	LastName  string
	Notes     sql.NullString
}

func (q *Queries) GetPersonByFname(ctx context.Context, concat interface{}) ([]GetPersonByFnameRow, error) {
	rows, err := q.db.QueryContext(ctx, getPersonByFname, concat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPersonByFnameRow
	for rows.Next() {
		var i GetPersonByFnameRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPersonByFullname = `-- name: GetPersonByFullname :many
SELECT id, first_name, last_name, notes FROM person WHERE first_name LIKE ? AND last_name LIKE ?
`

type GetPersonByFullnameParams struct {
	FirstName string
	LastName  string
}

type GetPersonByFullnameRow struct {
	ID        int32
	FirstName string
	LastName  string
	Notes     sql.NullString
}

func (q *Queries) GetPersonByFullname(ctx context.Context, arg GetPersonByFullnameParams) ([]GetPersonByFullnameRow, error) {
	rows, err := q.db.QueryContext(ctx, getPersonByFullname, arg.FirstName, arg.LastName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPersonByFullnameRow
	for rows.Next() {
		var i GetPersonByFullnameRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPersonByLname = `-- name: GetPersonByLname :many
SELECT id, first_name, last_name, notes FROM person WHERE last_name LIKE ?
`

type GetPersonByLnameRow struct {
	ID        int32
	FirstName string
	LastName  string
	Notes     sql.NullString
}

func (q *Queries) GetPersonByLname(ctx context.Context, lastName string) ([]GetPersonByLnameRow, error) {
	rows, err := q.db.QueryContext(ctx, getPersonByLname, lastName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPersonByLnameRow
	for rows.Next() {
		var i GetPersonByLnameRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPersonPhones = `-- name: GetPersonPhones :many
SELECT phone_number, phone_type FROM phone WHERE person_id = ?
`

type GetPersonPhonesRow struct {
	PhoneNumber string
	PhoneType   int32
}

func (q *Queries) GetPersonPhones(ctx context.Context, personID int32) ([]GetPersonPhonesRow, error) {
	rows, err := q.db.QueryContext(ctx, getPersonPhones, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPersonPhonesRow
	for rows.Next() {
		var i GetPersonPhonesRow
		if err := rows.Scan(&i.PhoneNumber, &i.PhoneType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
